Feature/293 adding validation password change
akvo/rtmis pull request #295
Opened 2022-04-25 13:16 UTC by abhishek-p-s

2022-04-25 20:08 UTC, dedenbangkit commented
The PR should be to develop branch

2022-04-26 06:57 UTC, mantiz8x requested changes

2022-04-26 06:57 UTC, mantiz8x commented on frontend/src/pages/login/components/RegistrationForm.jsx
> +  { name: "Upercase Character", re: /[A-Z]/ },
Fix typo

2022-04-26 06:57 UTC, mantiz8x commented on frontend/src/pages/login/components/RegistrationForm.jsx
>  ];
Add a rule for minimum 8 characters

2022-04-26 08:26 UTC, mantiz8x approved these changes

2022-04-26 13:07 UTC, merged