Feature/547 tests for Library folder
akvo/rtmis pull request #555
Opened 2022-07-06 14:13 UTC by lightme-fan

## Tests in the `/lib` folder
- [x] api.test.js
- [x] geo.test.js
- [x] store.test.js
- [x] queue.test.js
- [x] ui-text.test.js

![Screenshot 2022-07-06 17:02:45](https://user-images.githubusercontent.com/60210180/177569028-b17092cb-b6f8-4388-b586-062e0315f776.png)

2022-07-07 04:56 UTC, dedenbangkit requested changes
Please check the comment @lightme-fan

2022-07-07 04:56 UTC, dedenbangkit commented on frontend/src/lib/geo.js
> +export const getBounds = (administration) => {
Why do you need to export this? getBounds is already part of geo.

geo.getBounds()

2022-07-07 04:56 UTC, dedenbangkit commented on frontend/src/lib/geo.js
> +export const defaultPos = () => {
same as above

2022-07-07 04:56 UTC, dedenbangkit commented on frontend/src/pages/login/__test__/Login.test.js
> -import { render, screen } from "@testing-library/react";
Why you remove this?

2022-07-07 04:56 UTC, dedenbangkit commented on frontend/src/pages/login/__test__/__snapshots__/Login.test.js.snap
> -// Jest Snapshot v1, https://goo.gl/fbAQLP
And also we need a snapshot, this is the example test I made

2022-07-07 05:12 UTC, lightme-fan commented
Thanks for the comments. Fixing them now.

2022-08-25 08:07 UTC, dedenbangkit approved these changes

2022-08-25 08:07 UTC, merged