[#686] Transform all JMP to category.json
akvo/rtmis pull request #688
Opened 2023-05-29 13:34 UTC by ifirmawan

## TODO/DONE

Transform all JMP to category.json

- [x] Household
- [x] Wash in schools
- [x] Urban sanitation

* Note:  Health facilities has been transformed as initial category.json

2023-05-29 14:48 UTC, dedenbangkit requested changes
@ifirmawan please re-check the structure for overall categories, some of them are miss-match. e.g:
- "No Service" become `false` in Health Facilities for Sanitation category.
or; perhaps seeder doesn't comply the dependency structure.

2023-05-29 15:02 UTC, dedenbangkit requested changes
@ifirmawan please re-check the structure for overall categories, some of them are miss-match. e.g:
- "No Service" become `false` in Health Facilities for Sanitation category.
or; perhaps seeder doesn't comply the dependency structure.

2023-05-30 02:45 UTC, ifirmawan commented
> @ifirmawan please re-check the structure for overall categories, some of them are miss-match. e.g:
> 
> * "No Service" become `false` in Health Facilities for Sanitation category.
>   or; perhaps seeder doesn't comply the dependency structure.

Hi mas @dedenbangkit, I can confirm this issue from the category.json, I've fixed it and added more tests

2023-05-30 04:17 UTC, dedenbangkit approved these changes

2023-05-30 04:17 UTC, merged